# Generated by Django 4.2 on 2023-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0002_student_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=20)),
                ("execution_time", models.FloatField()),
            ],
        ),
    ]
